name: flox publish

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
          - runner: ubuntu-24.04-arm
          - runner: macos-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Install Flox
        uses: flox/install-flox-action@v2
      - name: Publish to Flox Catalog
        run: flox publish --org devbytes freight
        env:
          FLOX_FLOXHUB_TOKEN: ${{ secrets.FLOX_FLOXHUB_TOKEN }}
